[workspace]
members = [
  "iroh",
  "iroh-api",
  "iroh-bitswap",
  "iroh-car",
  "iroh-rpc-client",
  "iroh-rpc-types",
  "iroh-gateway",
  "iroh-metrics",
  "iroh-one",
  "iroh-p2p",
  "iroh-resolver",
  "iroh-store",
  "iroh-share",
  "iroh-util",
  "stores/*",
  "examples"
]
# even if all crates are set to edition 2021, we still need to force the
# resolver to 2
# https://github.com/gfx-rs/wgpu/issues/2356#issuecomment-1005134986
resolver = "2"

[patch.crates-io]
libp2p = { git = "https://github.com/dignifiedquire/rust-libp2p", branch = "iroh-0-49" }
# libp2p = { path = "../rust-libp2p" }
